### PR TITLE
free(dir) was giving me trouble

### PR DESCRIPTION
**Pull request by NateBrune**
Sorry if I am wrong, I am a novice at this kind of stuff, but uh... `make` was failing and I traced it back to this. I think the bug is related to this: http://stackoverflow.com/questions/20297524/c-free-invalid-pointer

Here is a mirror of the errors I received: http://pastebin.com/qWNX5Pyy 
if they are any help.
I _think_ i got it, but sorry if I bugged you and I am wrong :(

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Removing the free and leaking memory is not an acceptable solution.

**Comment by SirCmpwn** [comment]
Despite this not being an acceptable solution, I do want to help you find out what's wrong. I fixed a memory corruption problem last night, can you make sure you're on the latest version of kpack?

**Comment by NateBrune** [comment]
So... looks like it was on my end (yay?) I was able to compile it on another machine just fine so I don't know what is up with that. Thank you very much for being so awesome and continuing development of this awesome project. Also thank you for responding to my request in a friendly and timely manor, It means a lot :) Keep on keeping on!

PS: I am on a buggy machine with buggy hardware, a custom linux kernel, any number of things could be wrong, for all I know I just need a reboot. Super sorry for wasting your time

**Comment by SirCmpwn** [comment]
It's all good.

**Pull request closed without merging**
